package library_project;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dubs
 */
public class MainForm extends javax.swing.JFrame {

    DefaultTableModel model;

    /**
     * Creates new form Main_Form
     */
    public MainForm() {
        initComponents();
        findOeuvres();
    }

    
// get a list of users from mysql database

    public ArrayList<Oeuvre> ListOeuvres(String ValToSearch) {
        ArrayList<Oeuvre> oeuvresList = new ArrayList<Oeuvre>();
        Statement st = null;
        ResultSet rs;
        
        try{
            
            String searchQuery = "SELECT * FROM `users` WHERE (`id`|| `fname`|| `lname`|| `age`) LIKE '%"+ValToSearch+"%'";
            rs = st.executeQuery(searchQuery);
            
            Oeuvre oeuvre;
      

            while (rs.next()) {
                oeuvre = new Oeuvre(
                        rs.getInt("id"),
                        rs.getString("titre"),
                        rs.getInt("date_parution"),
                        rs.getString("commentaire"),
                        rs.getInt("note")
                );
                oeuvresList.add(oeuvre);
            }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

        return oeuvresList;

   
}

    // Filter Data In Jtable
    private void findOeuvres() {
        ArrayList<Oeuvre> oeuvres = ListOeuvres(jTextField_MainSearch.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Id", "Titre", "Annee", "Commentaire", "Note"});
        Object[] row = new Object[5];

        for (int i = 0; i < oeuvres.size(); i++) {
            row[0] = oeuvres.get(i).getId();
            row[1] = oeuvres.get(i).getTitre();
            row[2] = oeuvres.get(i).getAnnee();
            row[3] = oeuvres.get(i).getCommentaire();
            row[4] = oeuvres.get(i).getNote();
            model.addRow(row);
        }
        jTable_MainOeuvres.setModel(model);
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_MainSearch = new javax.swing.JButton();
        jButton_Livres = new javax.swing.JButton();
        jButton_Musiques = new javax.swing.JButton();
        jButton_Films = new javax.swing.JButton();
        jButton_Jeux = new javax.swing.JButton();
        jTextField_MainSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_MainOeuvres = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jButton_MainSearch.setText("MainSearch");
        jButton_MainSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MainSearchActionPerformed(evt);
            }
        });

        jButton_Livres.setText("Livres");
        jButton_Livres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LivresActionPerformed(evt);
            }
        });

        jButton_Musiques.setText("Musiques");
        jButton_Musiques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MusiquesActionPerformed(evt);
            }
        });

        jButton_Films.setText("Films");
        jButton_Films.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FilmsActionPerformed(evt);
            }
        });

        jButton_Jeux.setText("JeuxVideo");
        jButton_Jeux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_JeuxActionPerformed(evt);
            }
        });

        jTextField_MainSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MainSearchActionPerformed(evt);
            }
        });

        jTable_MainOeuvres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        jTable_MainOeuvres.setGridColor(new java.awt.Color(204, 204, 204));
        jTable_MainOeuvres.getTableHeader().setBackground(Color.BLACK);
        jTable_MainOeuvres.getTableHeader().setForeground(Color.WHITE);
        jTable_MainOeuvres.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable_MainOeuvres);
        if (jTable_MainOeuvres.getColumnModel().getColumnCount() > 0) {
            jTable_MainOeuvres.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            jTable_MainOeuvres.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            jTable_MainOeuvres.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            jTable_MainOeuvres.getColumnModel().getColumn(3).setHeaderValue("Title 4");
            jTable_MainOeuvres.getColumnModel().getColumn(4).setHeaderValue("Title 5");
            jTable_MainOeuvres.getColumnModel().getColumn(5).setHeaderValue("Title 6");
            jTable_MainOeuvres.getColumnModel().getColumn(6).setHeaderValue("Title 7");
            jTable_MainOeuvres.getColumnModel().getColumn(7).setHeaderValue("Title 8");
            jTable_MainOeuvres.getColumnModel().getColumn(8).setHeaderValue("Title 9");
            jTable_MainOeuvres.getColumnModel().getColumn(9).setHeaderValue("Title 10");
            jTable_MainOeuvres.getColumnModel().getColumn(10).setHeaderValue("Title 11");
            jTable_MainOeuvres.getColumnModel().getColumn(11).setHeaderValue("Title 12");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Livres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Musiques)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Films)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Jeux)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                        .addComponent(jButton_MainSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_MainSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_MainSearch)
                    .addComponent(jTextField_MainSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Livres)
                    .addComponent(jButton_Musiques)
                    .addComponent(jButton_Films)
                    .addComponent(jButton_Jeux))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(0, 0, 1194, 665);
    }// </editor-fold>//GEN-END:initComponents
    }
    private void jButton_MainSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MainSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_MainSearchActionPerformed

    private void jButton_LivresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LivresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_LivresActionPerformed

    private void jButton_MusiquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MusiquesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_MusiquesActionPerformed

    private void jButton_FilmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FilmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_FilmsActionPerformed

    private void jButton_JeuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_JeuxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_JeuxActionPerformed

    private void jTextField_MainSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MainSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MainSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Films;
    private javax.swing.JButton jButton_Jeux;
    private javax.swing.JButton jButton_Livres;
    private javax.swing.JButton jButton_MainSearch;
    private javax.swing.JButton jButton_Musiques;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_MainOeuvres;
    private javax.swing.JTextField jTextField_MainSearch;
    // End of variables declaration//GEN-END:variables


}
